/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  // Emit a self-contained server bundle; required by the multi-stage Dockerfile.
  output: 'standalone',
  images: {
    // Serve AVIF first (25–50 % smaller than WebP), fall back to WebP.
    // First request per image takes slightly longer to encode; subsequent
    // requests hit the disk cache and serve instantly.
    formats: ['image/avif', 'image/webp'],

    // Keep optimised images in the Next.js disk cache for 1 year.
    // All admin-uploaded URLs include a timestamp component, so the URL
    // changes whenever an image is replaced — long TTL is safe here.
    minimumCacheTTL: 60 * 60 * 24 * 365, // 31 536 000 s

    // Standard responsive breakpoints — no change from Next.js defaults,
    // listed explicitly so they are obvious and easy to tune.
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],

    // Allow next/image to load images from Supabase Storage public URLs.
    // Wildcard host covers any Supabase project ref; path is scoped to the
    // public object endpoint. Without this, every product/category/hero/
    // play-area image uploaded via the admin panel crashes the page that
    // renders it ("hostname is not configured under images in next.config.js").
    remotePatterns: [
      // Original public URLs (stored in the DB, used as base for transforms).
      {
        protocol: 'https',
        hostname: '*.supabase.co',
        pathname: '/storage/v1/object/public/**',
      },
      // CDN transform endpoint — generated by toSupabaseTransformUrl() and
      // passed as `src` to next/image so the optimizer fetches a pre-sized
      // image from Supabase CDN instead of the raw (potentially huge) original.
      {
        protocol: 'https',
        hostname: '*.supabase.co',
        pathname: '/storage/v1/render/image/public/**',
      },
    ],
    // The bundled hero artwork is SVG, and admins may upload SVG logos/banners.
    // next/image refuses SVGs by default (returns 400 → broken images). Allow
    // them, but neutralise the XSS risk: force download disposition + a strict
    // CSP/sandbox so any embedded script can never execute when optimised.
    dangerouslyAllowSVG: true,
    contentDispositionType: 'attachment',
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
}

module.exports = nextConfig
